print("Operador and")
print(True, " and ", True, " = ", (True and True))
print(True, " and ", False, " = ", (True and False))
print(False, " and ", True, " = ", (False and True))
print(False, " and ", False, " = ", (False and False))

print("Operador or")
print(True, " or ", True, " = ", (True or True))
print(True, " or ", False, " = ", (True or False))
print(False, " or ", True, " = ", (False or True))
print(False, " or ", False, " = ", (False or False))

print("Operador not")
print("not ", True, " = ", (not True))
print("not ", False, " = ", (not False))
